In [1]:
import json
import pandas as pd
import mysql.connector
import numpy as np
pd.set_option('display.max_rows', None)

In [2]:
conn=mysql.connector.connect(host="119.18.54.55",
                            user="finqy5uy_remote",
                            password="aiYfABQnwK",
                            database="finqy5uy_erbprod")

In [3]:
df=pd.read_sql("select * from score_me",conn)

In [4]:
df.head()

,id,lead_id,ref_id,stage,response,report,date,product
0,2,240400,e9dfecc2-e645-4a45-99bc-11b3edf5c36a,2,"{\n ""Data"": {\n ""Account Details"": {\n ...",PL00002404_scoreme_report.pdf,2021-09-26,pl
1,4,240411,89a1243a-9a1d-40df-9dde-b44538016471,2,,,2021-09-28,
2,9,240422,81ec4e16-76da-48be-9534-c18369aa28f8,2,"{\n ""Data"": {\n ""Account Details"": {\n ...",,2021-09-28,pl
3,10,240433,61895917-722a-4845-bcbf-54655cb639ca,2,"{\n ""Data"": {\n ""Account Details"": {\n ...",PL00002404_scoreme_report.pdf,2021-09-28,pl
4,11,240444,00b2b54d-728d-4a3a-b418-3ecbb46439a0,1,,PL00002404_scoreme_report.pdf,2021-09-30,

In [5]:
df.replace("",np.nan,regex=True, inplace=True)

In [6]:
df.head()

,id,lead_id,ref_id,stage,response,report,date,product
0,2,240400,e9dfecc2-e645-4a45-99bc-11b3edf5c36a,2,"{\n ""Data"": {\n ""Account Details"": {\n ...",PL00002404_scoreme_report.pdf,2021-09-26,pl
1,4,240411,89a1243a-9a1d-40df-9dde-b44538016471,2,NaN,NaN,2021-09-28,NaN
2,9,240422,81ec4e16-76da-48be-9534-c18369aa28f8,2,"{\n ""Data"": {\n ""Account Details"": {\n ...",NaN,2021-09-28,pl
3,10,240433,61895917-722a-4845-bcbf-54655cb639ca,2,"{\n ""Data"": {\n ""Account Details"": {\n ...",PL00002404_scoreme_report.pdf,2021-09-28,pl
4,11,240444,00b2b54d-728d-4a3a-b418-3ecbb46439a0,1,NaN,PL00002404_scoreme_report.pdf,2021-09-30,NaN

In [7]:
df.dropna(axis=0,subset=["response"], inplace=True)

In [8]:
df.head(20)

,id,lead_id,ref_id,stage,response,report,date,product
0,2,240400,e9dfecc2-e645-4a45-99bc-11b3edf5c36a,2,"{\n ""Data"": {\n ""Account Details"": {\n ...",PL00002404_scoreme_report.pdf,2021-09-26,pl
2,9,240422,81ec4e16-76da-48be-9534-c18369aa28f8,2,"{\n ""Data"": {\n ""Account Details"": {\n ...",NaN,2021-09-28,pl
3,10,240433,61895917-722a-4845-bcbf-54655cb639ca,2,"{\n ""Data"": {\n ""Account Details"": {\n ...",PL00002404_scoreme_report.pdf,2021-09-28,pl
6,13,2404666,83c6e979-3bb6-4647-8964-5dd8e550122d,2,"{\n ""Data"": {\n ""Account Details"": {\n ...",PL00002404_scoreme_report.pdf,2021-09-30,pl
7,14,2404,b6ee3124-cb0e-479d-a751-91b3dd4edafc,2,"{\n ""Data"": {\n ""Account Details"": {\n ...",PL00002404_scoreme_report.pdf,2021-10-01,pl
10,17,2595,7fdb6004-e83f-40f0-8024-180d7f017e6b,2,"{\n ""Data"": {\n ""Account Details"": {\n ...",PL00002595_scoreme_report.pdf,2021-10-13,pl
11,18,2924,43fcb310-6455-486b-b505-9267922a718a,2,"{\n ""Data"": {\n ""Account Details"": {\n ...",PL00002924_scoreme_report.pdf,2021-11-16,pl
13,20,2938,bdc77f10-ff43-41ad-ac7d-08407e4eac71,2,"{\n ""Data"": {\n ""Account Details"": {\n ...",PL00002938_scoreme_report.pdf,2021-11-17,pl
18,25,2956,0528cd79-5acf-40aa-885a-e911a9108b7b,2,"{\n ""Data"": {\n ""Account Details"": {\n ...",PL00002956_scoreme_report.pdf,2021-11-19,pl
20,27,2967,ed2abe1e-6c4a-4609-840b-86cdb9d0c84a,2,"{\n ""Data"": {\n ""Account Details"": {\n ...",PL00002967_scoreme_report.pdf,2021-11-19,pl
21,28,2966,2badd62f-bc45-45e7-a8e9-7981b80ef256,2,"{\n ""Data"": {\n ""Account Details"": {\n ...",PL00002966_scoreme_report.pdf,2021-11-20,pl
22,29,2968,45bb45ce-1ca1-4ab5-88d4-1285302dfdfc,2,"{\n ""Data"": {\n ""Account Details"": {\n ...",PL00002968_scoreme_report.pdf,2021-11-20,pl
23,30,2973,9351f1fa-d04c-4327-9a0d-087cd74d27c7,2,"{\n ""Data"": {\n ""Account Details"": {\n ...",PL00002973_scoreme_report.pdf,2021-11-20,pl
24,31,2979,b0b1cab7-6370-48a2-b330-1c8a33a3aaf4,2,"{\n ""Data"": {\n ""Account Details"": {\n ...",PL00002979_scoreme_report.pdf,2021-11-20,pl
25,32,2985,90f13028-65f0-4f4c-8673-e1506bccb198,2,"{\n ""Data"": {\n ""Account Details"": {\n ...",PL00002985_scoreme_report.pdf,2021-11-22,pl
26,33,2988,01d57d9e-61a3-474a-a878-a48b54486368,2,"{\n ""Data"": {\n ""Account Details"": {\n ...",PL00002988_scoreme_report.pdf,2021-11-22,pl
28,35,2990,66540e3d-a263-460d-80dd-cefe3bb71bfc,2,"{\n ""Data"": {\n ""Account Details"": {\n ...",PL00002990_scoreme_report.pdf,2021-11-22,pl
30,37,2989,bb037924-1d03-49fd-8f7a-98f37f21b606,2,"{\n ""Data"": {\n ""Account Details"": {\n ...",PL00002989_scoreme_report.pdf,2021-11-22,pl
31,38,2993,12219e73-2d03-41da-acd5-024749951a3f,2,"{\n ""Data"": {\n ""Account Details"": {\n ...",PL00002993_scoreme_report.pdf,2021-11-23,pl
33,40,2996,03b839e6-0300-47a8-99ac-71aeedbea92e,2,"{\n ""Data"": {\n ""Account Details"": {\n ...",PL00002996_scoreme_report.pdf,2021-11-23,pl

In [9]:
df.nunique()

id          279
lead_id     279
ref_id      279
stage         1
response    274
report      235
date        124
product       2
dtype: int64

In [10]:
response = pd.DataFrame(df, columns=['lead_id',"response"])

In [11]:
response.head()

   lead_id                                           response
0   240400  {\n  "Data": {\n    "Account Details": {\n    ...
2   240422  {\n  "Data": {\n    "Account Details": {\n    ...
3   240433  {\n  "Data": {\n    "Account Details": {\n    ...
6  2404666  {\n  "Data": {\n    "Account Details": {\n    ...
7     2404  {\n  "Data": {\n    "Account Details": {\n    ...

In [12]:
lead_id = response["lead_id"]
lead_id.head()

0     240400
2     240422
3     240433
6    2404666
7       2404
Name: lead_id, dtype: object

In [13]:
response1 = response["response"].apply(json.loads)

In [14]:
data=response1[0]
print (data)

{'Data': {'Account Details': {'ClientName': 'ERB', 'BankName': 'ICICI Bank', 'Account No': '123456', 'Period': '2020-09-09-2021-03-06', 'No of months': '6', 'AccountType': 'SAVINGS', 'Currency': 'INR', 'Opening Balanace': '303.68', 'Closing Balance': '15544.89'}, 'Bank Statement': [{'Slno': 1, 'date': '09-Sep-2020', 'Particular': 'UPI/025306491215/UPI/prashanth.ch879/Central BankOf', 'Reference': None, 'Debit': 0.0, 'Credit': 11000.0, 'Balance': 11303.68, 'FirstLevelClassification': 'UPI Receipt', 'SecondLevelClassification': 'UPI Receipt'}, {'Slno': 2, 'date': '09-Sep-2020', 'Particular': 'BIL/INFT/002071084297/NA/ PRABHUDAS K CHE', 'Reference': None, 'Debit': 11000.0, 'Credit': 0.0, 'Balance': 303.68, 'FirstLevelClassification': 'Online Payment', 'SecondLevelClassification': 'Online Payment'}, {'Slno': 3, 'date': '16-Sep-2020', 'Particular': 'UPI/026000765346/UPI/prashanth.ch879/Central BankOf', 'Reference': None, 'Debit': 0.0, 'Credit': 20000.0, 'Balance': 20303.68, 'FirstLevelClassification': 'UPI Receipt', 'SecondLevelClassification': 'UPI Receipt'}, {'Slno': 4, 'date': '16-Sep-2020', 'Particular': 'BIL/002076096700/ICICI BANK CREDIT CA/437551554299', 'Reference': None, 'Debit': 13129.0, 'Credit': 0.0, 'Balance': 7174.68, 'FirstLevelClassification': 'Online Payment', 'SecondLevelClassification': 'Online Payment'}, {'Slno': 5, 'date': '23-Sep-2020', 'Particular': 'BIL/002080829970/ICICI BANK CREDIT CA/437551554299', 'Reference': None, 'Debit': 4324.0, 'Credit': 0.0, 'Balance': 2850.68, 'FirstLevelClassification': 'Online Payment', 'SecondLevelClassification': 'Online Payment'}, {'Slno': 6, 'date': '29-Sep-2020', 'Particular': '020201579346:Int.Pd:29-06-2020 to 28-09-2020', 'Reference': None, 'Debit': 0.0, 'Credit': 391.0, 'Balance': 3241.68, 'FirstLevelClassification': 'Interest Received', 'SecondLevelClassification': 'Interest Received'}, {'Slno': 7, 'date': '30-Sep-2020', 'Particular': 'ICSP/SALARY SEP2020', 'Reference': None, 'Debit': 0.0, 'Credit': 76551.0, 'Balance': 79792.68, 'FirstLevelClassification': 'Salary', 'SecondLevelClassification': 'Salary'}, {'Slno': 8, 'date': '30-Sep-2020', 'Particular': 'MMT/IMPS/027420779286/NA/Prashant C/CBIN0281262', 'Reference': None, 'Debit': 35000.0, 'Credit': 0.0, 'Balance': 44792.68, 'FirstLevelClassification': 'Mobile Payment', 'SecondLevelClassification': 'Mobile Payment'}, {'Slno': 9, 'date': '30-Sep-2020', 'Particular': 'MMT/IMPS/027420854059/NA/Lokesh/HDFC000008 0', 'Reference': None, 'Debit': 7715.0, 'Credit': 0.0, 'Balance': 37077.68, 'FirstLevelClassification': 'Mobile Payment', 'SecondLevelClassification': 'Mobile Payment'}, {'Slno': 10, 'date': '01-Oct-2020', 'Particular': 'MMT/IMPS/027512858516/NA/Prashant C/CBIN0281262', 'Reference': None, 'Debit': 4000.0, 'Credit': 0.0, 'Balance': 33077.68, 'FirstLevelClassification': 'Mobile Payment', 'SecondLevelClassification': 'Mobile Payment'}, {'Slno': 11, 'date': '05-Oct-2020', 'Particular': 'LPHYDXX98385 OCT20 Prashanth K', 'Reference': None, 'Debit': 32557.0, 'Credit': 0.0, 'Balance': 520.68, 'FirstLevelClassification': 'Online Payment', 'SecondLevelClassification': 'Online Payment'}, {'Slno': 12, 'date': '13-Oct-2020', 'Particular': 'MMT/IMPS/028720775036/NA/Prashant C/CBIN0281262', 'Reference': None, 'Debit': 520.0, 'Credit': 0.0, 'Balance': 0.68, 'FirstLevelClassification': 'Mobile Payment', 'SecondLevelClassification': 'Mobile Payment'}, {'Slno': 13, 'date': '29-Oct-2020', 'Particular': 'UPI/030302177645/UPI/prashanth.ch879/Central BankOf', 'Reference': None, 'Debit': 0.0, 'Credit': 20000.0, 'Balance': 20000.68, 'FirstLevelClassification': 'UPI Receipt', 'SecondLevelClassification': 'UPI Receipt'}, {'Slno': 14, 'date': '29-Oct-2020', 'Particular': 'UPI/030302180062/UPI/prashanth.ch879/Central BankOf', 'Reference': None, 'Debit': 0.0, 'Credit': 2100.0, 'Balance': 22100.68, 'FirstLevelClassification': 'UPI Receipt', 'SecondLevelClassification': 'UPI Receipt'}, {'Slno': 15, 'date': '29-Oct-2020', 'Particular': 'BIL/002108005000/ICICI BANK CREDIT CA/437551554299', 'Reference': None, 'Debit': 22066.0, 'Credit': 0.0, 'Balance': 34.68, 'FirstLevelClassification': 'Online Payment', 'SecondLevelClassification': 'Online Payment'}, {'Slno': 16, 'date': '29-Oct-2020', 'Particular': 'ICSP/SALARY OCT2020', 'Reference': None, 'Debit': 0.0, 'Credit': 74153.0, 'Balance': 74187.68, 'FirstLevelClassification': 'Salary', 'SecondLevelClassification': 'Salary'}, {'Slno': 17, 'date': '29-Oct-2020', 'Particular': 'MMT/IMPS/030323497261/NA/Prashant C/CBIN0281262', 'Reference': None, 'Debit': 16000.0, 'Credit': 0.0, 'Balance': 58187.68, 'FirstLevelClassification': 'Mobile Payment', 'SecondLevelClassification': 'Mobile Payment'}, {'Slno': 18, 'date': '30-Oct-2020', 'Particular': 'MMT/IMPS/030406900087/NA/Prashant C/CBIN0281262', 'Reference': None, 'Debit': 12000.0, 'Credit': 0.0, 'Balance': 46187.68, 'FirstLevelClassification': 'Mobile Payment', 'SecondLevelClassification': 'Mobile Payment'}, {'Slno': 19, 'date': '30-Oct-2020', 'Particular': 'MMT/IMPS/030409174260/NA/Lokesh/HDFC000008 0', 'Reference': None, 'Debit': 2000.0, 'Credit': 0.0, 'Balance': 44187.68, 'FirstLevelClassification': 'Mobile Payment', 'SecondLevelClassification': 'Mobile Payment'}, {'Slno': 20, 'date': '30-Oct-2020', 'Particular': 'MMT/IMPS/030420364788/NA/Prashant C/CBIN0281262', 'Reference': None, 'Debit': 5000.0, 'Credit': 0.0, 'Balance': 39187.68, 'FirstLevelClassification': 'Mobile Payment', 'SecondLevelClassification': 'Mobile Payment'}, {'Slno': 21, 'date': '03-Nov-2020', 'Particular': 'MMT/IMPS/030805919991/NA/Prashant C/CBIN0281262', 'Reference': None, 'Debit': 5000.0, 'Credit': 0.0, 'Balance': 34187.68, 'FirstLevelClassification': 'Mobile Payment', 'SecondLevelClassification': 'Mobile Payment'}, {'Slno': 22, 'date': '04-Nov-2020', 'Particular': 'MMT/IMPS/030913448825/NA/Prashant C/CBIN0281262', 'Reference': None, 'Debit': 5000.0, 'Credit': 0.0, 'Balance': 29187.68, 'FirstLevelClassification': 'Mobile Payment', 'SecondLevelClassification': 'Mobile Payment'}, {'Slno': 23, 'date': '04-Nov-2020', 'Particular': 'UPI/030915035227/UPI/prashanth.ch879/Central BankOf', 'Reference': None, 'Debit': 0.0, 'Credit': 10000.0, 'Balance': 39187.68, 'FirstLevelClassification': 'UPI Receipt', 'SecondLevelClassification': 'UPI Receipt'}, {'Slno': 24, 'date': '05-Nov-2020', 'Particular': 'LPHYDXX98385 NOV20 Prashanth K', 'Reference': None, 'Debit': 32557.0, 'Credit': 0.0, 'Balance': 6630.68, 'FirstLevelClassification': 'Online Payment', 'SecondLevelClassification': 'Online Payment'}, {'Slno': 25, 'date': '05-Nov-2020', 'Particular': 'MMT/IMPS/031012639170/NA/Prashant C/CBIN0281262', 'Reference': None, 'Debit': 3000.0, 'Credit': 0.0, 'Balance': 3630.68, 'FirstLevelClassification': 'Mobile Payment', 'SecondLevelClassification': 'Mobile Payment'}, {'Slno': 26, 'date': '06-Nov-2020', 'Particular': 'CMS/ LPHYD00041898385C999316767PRASHANTH K 173/', 'Reference': None, 'Debit': 0.0, 'Credit': 173.0, 'Balance': 3803.68, 'FirstLevelClassification': 'Online Receipt', 'SecondLevelClassification': 'Online Receipt'}, {'Slno': 27, 'date': '07-Nov-2020', 'Particular': 'MMT/IMPS/031215637240/NA/Prashant C/CBIN0281262', 'Reference': None, 'Debit': 3800.0, 'Credit': 0.0, 'Balance': 3.68, 'FirstLevelClassification': 'Mobile Payment', 'SecondLevelClassification': 'Mobile Payment'}, {'Slno': 28, 'date': '18-Nov-2020', 'Particular': 'UPI/032319520043/UPI/prashanth.ch879/Central BankOf', 'Reference': None, 'Debit': 0.0, 'Credit': 5500.0, 'Balance': 5503.68, 'FirstLevelClassification': 'UPI Receipt', 'SecondLevelClassification': 'UPI Receipt'}, {'Slno': 29, 'date': '19-Nov-2020', 'Particular': 'UPI/032402235438/UPI/prashanth.ch879/Central BankOf', 'Reference': None, 'Debit': 0.0, 'Credit': 10000.0, 'Balance': 15503.68, 'FirstLevelClassification': 'UPI Receipt', 'SecondLevelClassification': 'UPI Receipt'}, {'Slno': 30, 'date': '19-Nov-2020', 'Particular': 'BIL/002124954483/ICICI BANK CREDIT CA/437551554299', 'Reference': None, 'Debit': 14800.0, 'Credit': 0.0, 'Balance': 703.68, 'FirstLevelClassification': 'Online Payment', 'SecondLevelClassification': 'Online Payment'}, {'Slno': 31, 'date': '23-Nov-2020', 'Particular': 'CMS/ LPHYD00040886281C1009215090PRASHANTH K CH158', 'Reference': None, 'Debit': 0.0, 'Credit': 1588.0, 'Balance': 2291.68, 'FirstLevelClassification': 'Online Receipt', 'SecondLevelClassification': 'Online Receipt'}, {'Slno': 32, 'date': '24-Nov-2020', 'Particular': 'CMS/ LPSUR00039491553C1009256243PRASHANTH K CH614', 'Reference': None, 'Debit': 0.0, 'Credit': 614.0, 'Balance': 2905.68, 'FirstLevelClassification': 'Online Receipt', 'SecondLevelClassification': 'Online Receipt'}, {'Slno': 33, 'date': '24-Nov-2020', 'Particular': 'UPI/032918023296/UPI/prashanth.ch879/Central BankOf', 'Reference': None, 'Debit': 0.0, 'Credit': 7500.0, 'Balance': 10405.68, 'FirstLevelClassification': 'UPI Receipt', 'SecondLevelClassification': 'UPI Receipt'}, {'Slno': 34, 'date': '24-Nov-2020', 'Particular': 'MMT/IMPS/032918118164/NA/Dad/ANDB0002066', 'Reference': None, 'Debit': 10400.0, 'Credit': 0.0, 'Balance': 5.68, 'FirstLevelClassification': 'Mobile Payment', 'SecondLevelClassification': 'Mobile Payment'}, {'Slno': 35, 'date': '27-Nov-2020', 'Particular': 'ICSP/SALARY NOV2020', 'Reference': None, 'Debit': 0.0, 'Credit': 71742.0, 'Balance': 71747.68, 'FirstLevelClassification': 'Salary', 'SecondLevelClassification': 'Salary'}, {'Slno': 36, 'date': '27-Nov-2020', 'Particular': 'MMT/IMPS/033218468444/NA/Prashant C/CBIN0281262', 'Reference': None, 'Debit': 50000.0, 'Credit': 0.0, 'Balance': 21747.68, 'FirstLevelClassification': 'Mobile Payment', 'SecondLevelClassification': 'Mobile Payment'}, {'Slno': 37, 'date': '30-Nov-2020', 'Particular': 'MMT/IMPS/033413816087/NA/Prashant C/CBIN0281262', 'Reference': None, 'Debit': 21747.0, 'Credit': 0.0, 'Balance': 0.68, 'FirstLevelClassification': 'Mobile Payment', 'SecondLevelClassification': 'Mobile Payment'}, {'Slno': 38, 'date': '30-Nov-2020', 'Particular': 'UPI/033422906371/UPI/prashanth.ch879/Central BankOf', 'Reference': None, 'Debit': 0.0, 'Credit': 20000.0, 'Balance': 20000.68, 'FirstLevelClassification': 'UPI Receipt', 'SecondLevelClassification': 'UPI Receipt'}, {'Slno': 39, 'date': '30-Nov-2020', 'Particular': 'UPI/033422916134/UPI/prashanth.ch879/Central BankOf', 'Reference': None, 'Debit': 0.0, 'Credit': 9530.0, 'Balance': 29530.68, 'FirstLevelClassification': 'UPI Receipt', 'SecondLevelClassification': 'UPI Receipt'}, {'Slno': 40, 'date': '30-Nov-2020', 'Particular': 'BIL/002132127346/ICICI BANK CREDIT CA/437551554299', 'Reference': None, 'Debit': 29509.0, 'Credit': 0.0, 'Balance': 21.68, 'FirstLevelClassification': 'Online Payment', 'SecondLevelClassification': 'Online Payment'}, {'Slno': 41, 'date': '01-Dec-2020', 'Particular': 'CMS/ VLC27112020561459/ICICI LOMBARD GENERAL INSU', 'Reference': None, 'Debit': 0.0, 'Credit': 3480.0, 'Balance': 3501.68, 'FirstLevelClassification': 'Insurance', 'SecondLevelClassification': 'Insurance'}, {'Slno': 42, 'date': '03-Dec-2020', 'Particular': 'UPI/033816211115/UPI/prashanth.ch879/Central BankOf', 'Reference': None, 'Debit': 0.0, 'Credit': 20000.0, 'Balance': 23501.68, 'FirstLevelClassification': 'UPI Receipt', 'SecondLevelClassification': 'UPI Receipt'}, {'Slno': 43, 'date': '03-Dec-2020', 'Particular': 'UPI/033816216988/UPI/prashanth.ch879/Central BankOf', 'Reference': None, 'Debit': 0.0, 'Credit': 10000.0, 'Balance': 33501.68, 'FirstLevelClassification': 'UPI Receipt', 'SecondLevelClassification': 'UPI Receipt'}, {'Slno': 44, 'date': '05-Dec-2020', 'Particular': 'UPI/034004458797/UPI/prashanth.ch879/Central BankOf', 'Reference': None, 'Debit': 0.0, 'Credit': 10000.0, 'Balance': 43501.68, 'FirstLevelClassification': 'UPI Receipt', 'SecondLevelClassification': 'UPI Receipt'}, {'Slno': 45, 'date': '05-Dec-2020', 'Particular': 'MMT/IMPS/034004157952/NA/Dad/ANDB0002066', 'Reference': None, 'Debit': 10000.0, 'Credit': 0.0, 'Balance': 33501.68, 'FirstLevelClassification': 'Mobile Payment', 'SecondLevelClassification': 'Mobile Payment'}, {'Slno': 46, 'date': '05-Dec-2020', 'Particular': 'LPHYDXX98385 DEC20 Prashanth K', 'Reference': None, 'Debit': 32557.0, 'Credit': 0.0, 'Balance': 944.68, 'FirstLevelClassification': 'Online Payment', 'SecondLevelClassification': 'Online Payment'}, {'Slno': 47, 'date': '16-Dec-2020', 'Particular': 'UPI/035113065133/UPI/prashanth.ch879/Central BankOf', 'Reference': None, 'Debit': 0.0, 'Credit': 20000.0, 'Balance': 20944.68, 'FirstLevelClassification': 'UPI Receipt', 'SecondLevelClassification': 'UPI Receipt'}, {'Slno': 48, 'date': '16-Dec-2020', 'Particular': 'UPI/035113075382/UPI/prashanth.ch879/Central BankOf', 'Reference': None, 'Debit': 0.0, 'Credit': 9000.0, 'Balance': 29944.68, 'FirstLevelClassification': 'UPI Receipt', 'SecondLevelClassification': 'UPI Receipt'}, {'Slno': 49, 'date': '16-Dec-2020', 'Particular': 'BIL/002146175801/ICICI BANK CREDIT CA/437551554299', 'Reference': None, 'Debit': 29509.0, 'Credit': 0.0, 'Balance': 435.68, 'FirstLevelClassification': 'Online Payment', 'SecondLevelClassification': 'Online Payment'}, {'Slno': 50, 'date': '30-Dec-2020', 'Particular': '020201579346:Int.Pd:29-09-2020 to 29-12-2020', 'Reference': None, 'Debit': 0.0, 'Credit': 51.0, 'Balance': 486.68, 'FirstLevelClassification': 'Interest Received', 'SecondLevelClassification': 'Interest Received'}, {'Slno': 51, 'date': '31-Dec-2020', 'Particular': 'ICSP/SALARY DEC2020', 'Reference': None, 'Debit': 0.0, 'Credit': 95366.0, 'Balance': 95852.68, 'FirstLevelClassification': 'Salary', 'SecondLevelClassification': 'Salary'}, {'Slno': 52, 'date': '31-Dec-2020', 'Particular': 'MMT/IMPS/036622531909/NA/Prashant C/CBIN0281262', 'Reference': None, 'Debit': 65000.0, 'Credit': 0.0, 'Balance': 30852.68, 'FirstLevelClassification': 'Mobile Payment', 'SecondLevelClassification': 'Mobile Payment'}, {'Slno': 53, 'date': '02-Jan-2021', 'Particular': 'MMT/IMPS/100212275277/NA/Prashant C/CBIN0281262', 'Reference': None, 'Debit': 30850.0, 'Credit': 0.0, 'Balance': 2.68, 'FirstLevelClassification': 'Mobile Payment', 'SecondLevelClassification': 'Mobile Payment'}, {'Slno': 54, 'date': '02-Jan-2021', 'Particular': 'UPI/100213823924/UPI/prashanth.ch879/Central BankOf', 'Reference': None, 'Debit': 0.0, 'Credit': 10000.0, 'Balance': 10002.68, 'FirstLevelClassification': 'UPI Receipt', 'SecondLevelClassification': 'UPI Receipt'}, {'Slno': 55, 'date': '02-Jan-2021', 'Particular': 'MMT/IMPS/100213339129/NA/Dad/ANDB0002066', 'Reference': None, 'Debit': 10000.0, 'Credit': 0.0, 'Balance': 2.68, 'FirstLevelClassification': 'Mobile Payment', 'SecondLevelClassification': 'Mobile Payment'}, {'Slno': 56, 'date': '02-Jan-2021', 'Particular': 'UPI/100216764819/UPI/prashanth.ch879/Central BankOf', 'Reference': None, 'Debit': 0.0, 'Credit': 20000.0, 'Balance': 20002.68, 'FirstLevelClassification': 'UPI Receipt', 'SecondLevelClassification': 'UPI Receipt'}, {'Slno': 57, 'date': '02-Jan-2021', 'Particular': 'UPI/100216807814/UPI/prashanth.ch879/Central BankOf', 'Reference': None, 'Debit': 0.0, 'Credit': 10000.0, 'Balance': 30002.68, 'FirstLevelClassification': 'UPI Receipt', 'SecondLevelClassification': 'UPI Receipt'}, {'Slno': 58, 'date': '04-Jan-2021', 'Particular': 'UPI/100311374980/UPI/prashanth.ch879/Central BankOf', 'Reference': None, 'Debit': 0.0, 'Credit': 20000.0, 'Balance': 50002.68, 'FirstLevelClassification': 'UPI Receipt', 'SecondLevelClassification': 'UPI Receipt'}, {'Slno': 59, 'date': '04-Jan-2021', 'Particular': 'UPI/100311382384/UPI/prashanth.ch879/Central BankOf', 'Reference': None, 'Debit': 0.0, 'Credit': 20000.0, 'Balance': 70002.68, 'FirstLevelClassification': 'UPI Receipt', 'SecondLevelClassification': 'UPI Receipt'}, {'Slno': 60, 'date': '04-Jan-2021', 'Particular': 'BIL/INFT/000011708464/NA/ PRABHUDAS K CHE', 'Reference': None, 'Debit': 40000.0, 'Credit': 0.0, 'Balance': 30002.68, 'FirstLevelClassification': 'Online Payment', 'SecondLevelClassification': 'Online Payment'}, {'Slno': 61, 'date': '04-Jan-2021', 'Particular': 'UPI/100411281496/UPI/prashanth.ch879/Central BankOf', 'Reference': None, 'Debit': 0.0, 'Credit': 3000.0, 'Balance': 33002.68, 'FirstLevelClassification': 'UPI Receipt', 'SecondLevelClassification': 'UPI Receipt'}, {'Slno': 62, 'date': '04-Jan-2021', 'Particular': 'CMS/ VLC31122020566707/ICICI LOMBARD GENERAL INSU', 'Reference': None, 'Debit': 0.0, 'Credit': 3495.0, 'Balance': 36497.68, 'FirstLevelClassification': 'Insurance', 'SecondLevelClassification': 'Insurance'}, {'Slno': 63, 'date': '05-Jan-2021', 'Particular': 'LPHYDXX98385 JAN21 Prashanth K', 'Reference': None, 'Debit': 32557.0, 'Credit': 0.0, 'Balance': 3940.68, 'FirstLevelClassification': 'Online Payment', 'SecondLevelClassification': 'Online Payment'}, {'Slno': 64, 'date': '08-Jan-2021', 'Particular': 'MMT/IMPS/100813470529/NA/Prashant C/CBIN0281262', 'Reference': None, 'Debit': 3900.0, 'Credit': 0.0, 'Balance': 40.68, 'FirstLevelClassification': 'Mobile Payment', 'SecondLevelClassification': 'Mobile Payment'}, {'Slno': 65, 'date': '18-Jan-2021', 'Particular': 'UPI/101713261288/UPI/prashanth.ch879/Central BankOf', 'Reference': None, 'Debit': 0.0, 'Credit': 2000.0, 'Balance': 2040.68, 'FirstLevelClassification': 'UPI Receipt', 'SecondLevelClassification': 'UPI Receipt'}, {'Slno': 66, 'date': '18-Jan-2021', 'Particular': 'BIL/000022803612/ICICI BANK CREDIT CA/437551554299', 'Reference': None, 'Debit': 2000.0, 'Credit': 0.0, 'Balance': 40.68, 'FirstLevelClassification': 'Online Payment', 'SecondLevelClassification': 'Online Payment'}, {'Slno': 67, 'date': '18-Jan-2021', 'Particular': 'UPI/101717861568/UPI/prashanth.ch879/Central BankOf', 'Reference': None, 'Debit': 0.0, 'Credit': 4500.0, 'Balance': 4540.68, 'FirstLevelClassification': 'UPI Receipt', 'SecondLevelClassification': 'UPI Receipt'}, {'Slno': 68, 'date': '18-Jan-2021', 'Particular': 'BIL/000022904974/ICICI BANK CREDIT CA/437551554299', 'Reference': None, 'Debit': 4530.0, 'Credit': 0.0, 'Balance': 10.68, 'FirstLevelClassification': 'Online Payment', 'SecondLevelClassification': 'Online Payment'}, {'Slno': 69, 'date': '18-Jan-2021', 'Particular': 'UPI/101817215987/UPI/prashanth.ch879/Central BankOf', 'Reference': None, 'Debit': 0.0, 'Credit': 5000.0, 'Balance': 5010.68, 'FirstLevelClassification': 'UPI Receipt', 'SecondLevelClassification': 'UPI Receipt'}, {'Slno': 70, 'date': '18-Jan-2021', 'Particular': 'BIL/000023566020/ICICI BANK CREDIT CA/437551554299', 'Reference': None, 'Debit': 5000.0, 'Credit': 0.0, 'Balance': 10.68, 'FirstLevelClassification': 'Online Payment', 'SecondLevelClassification': 'Online Payment'}, {'Slno': 71, 'date': '21-Jan-2021', 'Particular': 'UPI/102122678346/UPI/prashanth.ch879/Central BankOf', 'Reference': None, 'Debit': 0.0, 'Credit': 600.0, 'Balance': 610.68, 'FirstLevelClassification': 'UPI Receipt', 'SecondLevelClassification': 'UPI Receipt'}, {'Slno': 72, 'date': '21-Jan-2021', 'Particular': 'BIL/000025917498/ICICI BANK CREDIT CA/437551554299', 'Reference': None, 'Debit': 610.0, 'Credit': 0.0, 'Balance': 0.68, 'FirstLevelClassification': 'Online Payment', 'SecondLevelClassification': 'Online Payment'}, {'Slno': 73, 'date': '25-Jan-2021', 'Particular': 'UPI/102316027227/UPI/prashanth.ch879/Central BankOf', 'Reference': None, 'Debit': 0.0, 'Credit': 6000.0, 'Balance': 6000.68, 'FirstLevelClassification': 'UPI Receipt', 'SecondLevelClassification': 'UPI Receipt'}, {'Slno': 74, 'date': '25-Jan-2021', 'Particular': 'BIL/000026967481/ICICI BANK CREDIT CA/437551554299', 'Reference': None, 'Debit': 6000.0, 'Credit': 0.0, 'Balance': 0.68, 'FirstLevelClassification': 'Online Payment', 'SecondLevelClassification': 'Online Payment'}, {'Slno': 75, 'date': '29-Jan-2021', 'Particular': 'ICSP/SALARY JAN2021', 'Reference': None, 'Debit': 0.0, 'Credit': 76056.0, 'Balance': 76056.68, 'FirstLevelClassification': 'Salary', 'SecondLevelClassification': 'Salary'}, {'Slno': 76, 'date': '29-Jan-2021', 'Particular': 'MMT/IMPS/102919806731/NA/Prashant C/CBIN0281262'

In [15]:
Bank_name=data["Data"]["Account Details"]["BankName"]
Account_no=data["Data"]["Account Details"]["Account No"]
Account_type=data["Data"]["Account Details"]["AccountType"]
lead_id_0=response["lead_id"][0]

In [16]:
print(Bank_name,
Account_no,
Account_type,lead_id_0)

ICICI Bank 123456 SAVINGS 240400

In [17]:
len(response1)

279

In [18]:
Bank_name=[]
data1=[]
Account_no=[]
Account_type=[]
for i in response1:
    data1= i
    try:
        Account_no.append(data1["Data"]["Account Details"]["Account No"])
        Bank_name.append(data1["Data"]["Account Details"]["BankName"])
        Account_type.append(data1["Data"]["Account Details"]["AccountType"])
    except Exception as e:
        Account_no.append("Not Available")
        Bank_name.append("Not Available")
        Account_type.append("Not Available")

In [19]:
len(lead_id)

279

In [20]:
lead_id

0       240400
2       240422
3       240433
6      2404666
7         2404
10        2595
11        2924
13        2938
18        2956
20        2967
21        2966
22        2968
23        2973
24        2979
25        2985
26        2988
28        2990
30        2989
31        2993
33        2996
37        3003
44        3010
45        3017
47        3030
48        3048
49        3047
50        3044
54        3052
55        3075
57        3076
60        3083
62        3026
64        3088
65        3037
67        3063
68        3093
69        3092
75        3090
76        3105
80        3109
82        3113
84        3098
87        3122
88        3123
91        3130
93        3133
94        3135
96        3136
97        3138
98        3141
99        3139
103       3144
105       3157
109       3154
110       3148
111       3163
115       3146
116       3170
120       3177
121       3153
125       3185
126       3186
128       3194
129       3193
130       3192
131       3187
132       3184
133       3189
134       3182
136       3196
137       3201
138       3212
139       3213
140       3214
141       3215
142       3191
149       3221
150       3225
153       3229
154       3232
155       3233
156       3234
157       3235
158       3237
159       3242
160       3239
162       3250
163       3255
164       3251
167       3266
168       3265
169       3262
176       3272
177       3279
179       3273
181       3282
182       3283
184       3285
185       3290
186       3292
190       3264
192       3299
193       3301
196       3306
197       3309
199       3275
200       3312
205       3319
206       3320
207       3321
208       3322
210       3331
212       3339
213       3337
214       3338
215       3336
216       3353
217       3354
218       3352
219       3357
221       3335
223       3371
226       3378
227       3377
228       3379
231       3374
233       3388
236       3366
237       3372
238       3363
239       3342
243       3390
244        510
246       3417
247       3396
249        538
251       3435
255       3436
262        545
263        546
264        514
266       3455
275        555
281        558
282        559
286       3478
289       3502
299        569
304       3518
306       3496
311       3519
314       3533
316       3537
319       3541
320       3550
322       3557
333       3589
339        585
347       3608
350       3570
367        627
371       3656
374       3663
380       3677
392       3864
398       3870
403       3867
405       3866
408       3832
410       3890
413       3878
414       3875
415       3897
416       3896
420       3910
421       3911
423       3941
425        837
426       3949
428       3785
430       3966
431       3958
434       3988
437        866
439       4040
442       4051
443       3990
445       4058
446       4059
447       4039
448       4060
449       4061
450       4037
451       4066
453       4072
454       4064
455       4074
456       4080
457       4083
458       4068
460       4084
461       4053
462       4041
463       4093
464       4091
465       4062
466       4097
468        915
470       4105
472        897
473       4116
474       4114
475       4120
477       4090
479       4126
482       4128
484       4137
485       4139
486       4141
487       4136
488       4140
489       4118
490       4132
491       4101
492       4145
493       4131
496       4147
498       4144
501       3994
502       4160
523       4178
524        953
527        990
528       4247
531       4297
532       4316
533        967
534       4325
536       4329
537       4331
538       4332
539       4335
540       1014
541       4334
542       1016
545       4343
546       1003
547       1013
548       1018
549       4345
550       4363
551       4365
552       4362
553       4360
554       4241
555       4374
556       4381
557       4376
558       1029
559       1030
560       4399
563       4401
564       4387
565       4382
566       4384
567       4386
568       4389
569       4402
570       4400
571       4403
572       4404
573       4344
574       4409
575       4410
578       4411
579       4413
580       4414
581       4421
582       4431
Name: lead_id, dtype: object

In [21]:
lead_id1 =lead_id.tolist()

In [22]:
lead_id1

['240400',
 '240422',
 '240433',
 '2404666',
 '2404',
 '2595',
 '2924',
 '2938',
 '2956',
 '2967',
 '2966',
 '2968',
 '2973',
 '2979',
 '2985',
 '2988',
 '2990',
 '2989',
 '2993',
 '2996',
 '3003',
 '3010',
 '3017',
 '3030',
 '3048',
 '3047',
 '3044',
 '3052',
 '3075',
 '3076',
 '3083',
 '3026',
 '3088',
 '3037',
 '3063',
 '3093',
 '3092',
 '3090',
 '3105',
 '3109',
 '3113',
 '3098',
 '3122',
 '3123',
 '3130',
 '3133',
 '3135',
 '3136',
 '3138',
 '3141',
 '3139',
 '3144',
 '3157',
 '3154',
 '3148',
 '3163',
 '3146',
 '3170',
 '3177',
 '3153',
 '3185',
 '3186',
 '3194',
 '3193',
 '3192',
 '3187',
 '3184',
 '3189',
 '3182',
 '3196',
 '3201',
 '3212',
 '3213',
 '3214',
 '3215',
 '3191',
 '3221',
 '3225',
 '3229',
 '3232',
 '3233',
 '3234',
 '3235',
 '3237',
 '3242',
 '3239',
 '3250',
 '3255',
 '3251',
 '3266',
 '3265',
 '3262',
 '3272',
 '3279',
 '3273',
 '3282',
 '3283',
 '3285',
 '3290',
 '3292',
 '3264',
 '3299',
 '3301',
 '3306',
 '3309',
 '3275',
 '3312',
 '3319',
 '3320',
 '3321',
 '3322',
 '3331',
 '3339',
 '3337',
 '3338',
 '3336',
 '3353',
 '3354',
 '3352',
 '3357',
 '3335',
 '3371',
 '3378',
 '3377',
 '3379',
 '3374',
 '3388',
 '3366',
 '3372',
 '3363',
 '3342',
 '3390',
 '510',
 '3417',
 '3396',
 '538',
 '3435',
 '3436',
 '545',
 '546',
 '514',
 '3455',
 '555',
 '558',
 '559',
 '3478',
 '3502',
 '569',
 '3518',
 '3496',
 '3519',
 '3533',
 '3537',
 '3541',
 '3550',
 '3557',
 '3589',
 '585',
 '3608',
 '3570',
 '627',
 '3656',
 '3663',
 '3677',
 '3864',
 '3870',
 '3867',
 '3866',
 '3832',
 '3890',
 '3878',
 '3875',
 '3897',
 '3896',
 '3910',
 '3911',
 '3941',
 '837',
 '3949',
 '3785',
 '3966',
 '3958',
 '3988',
 '866',
 '4040',
 '4051',
 '3990',
 '4058',
 '4059',
 '4039',
 '4060',
 '4061',
 '4037',
 '4066',
 '4072',
 '4064',
 '4074',
 '4080',
 '4083',
 '4068',
 '4084',
 '4053',
 '4041',
 '4093',
 '4091',
 '4062',
 '4097',
 '915',
 '4105',
 '897',
 '4116',
 '4114',
 '4120',
 '4090',
 '4126',
 '4128',
 '4137',
 '4139',
 '4141',
 '4136',
 '4140',
 '4118',
 '4132',
 '4101',
 '4145',
 '4131',
 '4147',
 '4144',
 '3994',
 '4160',
 '4178',
 '953',
 '990',
 '4247',
 '4297',
 '4316',
 '967',
 '4325',
 '4329',
 '4331',
 '4332',
 '4335',
 '1014',
 '4334',
 '1016',
 '4343',
 '1003',
 '1013',
 '1018',
 '4345',
 '4363',
 '4365',
 '4362',
 '4360',
 '4241',
 '4374',
 '4381',
 '4376',
 '1029',
 '1030',
 '4399',
 '4401',
 '4387',
 '4382',
 '4384',
 '4386',
 '4389',
 '4402',
 '4400',
 '4403',
 '4404',
 '4344',
 '4409',
 '4410',
 '4411',
 '4413',
 '4414',
 '4421',
 '4431']

In [23]:
df=pd.DataFrame([lead_id1,Bank_name,Account_no,Account_type])

In [24]:
df.head()

,0,1,2,3,4,5,6,7,8,9,...,269,270,271,272,273,274,275,276,277,278
0,240400,240422,240433,2404666,2404,2595,2924,2938,2956,2967,...,4403,4404,4344,4409,4410,4411,4413,4414,4421,4431
1,ICICI Bank,ICICI Bank,ICICI Bank,ICICI Bank,ICICI Bank,HDFC Bank,HDFC Bank,ICICI Bank,Saraswat Co-operative Bank,State Bank of India,...,Punjab National Bank,HDFC Bank,Punjab National Bank,HDFC Bank,Saraswat Co-operative Bank,Union Bank of India,HDFC Bank,HDFC Bank,HDFC Bank,Bank of India
2,123456,123456,123456,123456,123456,1234589,123456,123456,123456,123456,...,12345,12345,12345,123456,12345,12345,12345,12345,12345,12345
3,SAVINGS,SAVINGS,SAVINGS,SAVINGS,SAVINGS,SAVINGS,SAVINGS,SAVINGS,SAVINGS,SAVINGS,...,SAVINGS,SAVINGS,SAVINGS,SAVINGS,SAVINGS,SAVINGS,SAVINGS,SAVINGS,SAVINGS,SAVINGS

In [25]:
tdf = df.T
print(tdf)

           0                            1              2              3
0     240400                   ICICI Bank         123456        SAVINGS
1     240422                   ICICI Bank         123456        SAVINGS
2     240433                   ICICI Bank         123456        SAVINGS
3    2404666                   ICICI Bank         123456        SAVINGS
4       2404                   ICICI Bank         123456        SAVINGS
5       2595                    HDFC Bank        1234589        SAVINGS
6       2924                    HDFC Bank         123456        SAVINGS
7       2938                   ICICI Bank         123456        SAVINGS
8       2956   Saraswat Co-operative Bank         123456        SAVINGS
9       2967          State Bank of India         123456        SAVINGS
10      2966                   ICICI Bank         123456        SAVINGS
11      2968                   ICICI Bank         123456        SAVINGS
12      2973                    HDFC Bank         123456        SAVINGS
13      2979                   ICICI Bank         123456        SAVINGS
14      2985               Karnataka Bank         123456        SAVINGS
15      2988                   ICICI Bank         123456        SAVINGS
16      2990                    HDFC Bank         123456        SAVINGS
17      2989                    HDFC Bank         123456        SAVINGS
18      2993          State Bank of India         123456        SAVINGS
19      2996                   ICICI Bank         123456        SAVINGS
20      3003          Kotak Mahindra Bank         123456        SAVINGS
21      3010                Bank of India         123456        SAVINGS
22      3017         Punjab National Bank         123456        SAVINGS
23      3030                   ICICI Bank         123456        SAVINGS
24      3048                    HDFC Bank         123456        SAVINGS
25      3047                    HDFC Bank         123456        SAVINGS
26      3044  Abhyudaya Co-operative Bank         123456        SAVINGS
27      3052                   ICICI Bank         123456        SAVINGS
28      3075          State Bank of India         123456        SAVINGS
29      3076               Bank of Baroda         123456        SAVINGS
30      3083                    HDFC Bank         123456        SAVINGS
31      3026          State Bank of India         123456        SAVINGS
32      3088                    HDFC Bank         123456        SAVINGS
33      3037                    HDFC Bank         123456        SAVINGS
34      3063                    HDFC Bank         123456        SAVINGS
35      3093          State Bank of India         123456        SAVINGS
36      3092                   ICICI Bank         123456        SAVINGS
37      3090                Bank of India         123456        SAVINGS
38      3105               Bank of Baroda         123456        SAVINGS
39      3109               Bank of Baroda         123456        SAVINGS
40      3113                Bank of India         123456        SAVINGS
41      3098                    HDFC Bank         123456        SAVINGS
42      3122                    HDFC Bank         123456        SAVINGS
43      3123                     Yes Bank         123456        SAVINGS
44      3130                   ICICI Bank         123456        SAVINGS
45      3133                Bank of India         123456        SAVINGS
46      3135                    HDFC Bank         123456        SAVINGS
47      3136          Kotak Mahindra Bank         123456        SAVINGS
48      3138                    Citi Bank         123456        SAVINGS
49      3141                    HDFC Bank         123456        SAVINGS
50      3139                   ICICI Bank         123456        SAVINGS
51      3144                    HDFC Bank         123456        SAVINGS
52      3157          State Bank of India         123456        SAVINGS
53      3154                   ICICI Bank         123456        SAVINGS
54      3148                    HDFC Bank         123456        SAVINGS
55      3163          Kotak Mahindra Bank         123456        SAVINGS
56      3146                    HDFC Bank         123456        SAVINGS
57      3170                    Citi Bank         123456        SAVINGS
58      3177                    HDFC Bank         123456        SAVINGS
59      3153                    HDFC Bank         123456        SAVINGS
60      3185                    HDFC Bank         123456        SAVINGS
61      3186               Bank of Baroda         123456        SAVINGS
62      3194                    HDFC Bank         123456        SAVINGS
63      3193                    HDFC Bank         123456        SAVINGS
64      3192          State Bank of India         123456        SAVINGS
65      3187                   ICICI Bank         123456        SAVINGS
66      3184          State Bank of India         123456        SAVINGS
67      3189                    HDFC Bank         123456        SAVINGS
68      3182                    HDFC Bank         123456        SAVINGS
69      3196               Bank of Baroda         123456        SAVINGS
70      3201                   ICICI Bank         123456        SAVINGS
71      3212              IDFC First Bank         123456        SAVINGS
72      3213                   ICICI Bank         123456        SAVINGS
73      3214          State Bank of India         123456        SAVINGS
74      3215                   ICICI Bank         123456        SAVINGS
75      3191          Kotak Mahindra Bank         123456        SAVINGS
76      3221               Bank of Baroda         123456        SAVINGS
77      3225         Punjab National Bank         123456        SAVINGS
78      3229                  Canara Bank         123456        SAVINGS
79      3232                    HDFC Bank         123456        SAVINGS
80      3233                    HDFC Bank         123456        SAVINGS
81      3234                  Canara Bank         123456        SAVINGS
82      3235                    HDFC Bank         123456        SAVINGS
83      3237          Bank of Maharashtra         123456        SAVINGS
84      3242       Janaseva Sahakari Bank         123456        SAVINGS
85      3239          State Bank of India         123456        SAVINGS
86      3250               Bank of Baroda         123456        SAVINGS
87      3255          State Bank of India         123456        SAVINGS
88      3251                Bank of India         123456        SAVINGS
89      3266                    HDFC Bank         123456        SAVINGS
90      3265                    HDFC Bank         123456        SAVINGS
91      3262          State Bank of India         123456        SAVINGS
92      3272                    HDFC Bank         123456        SAVINGS
93      3279                    HDFC Bank         123456        SAVINGS
94      3273          State Bank of India         123456        SAVINGS
95      3282                    HDFC Bank         123456        SAVINGS
96      3283          Kotak Mahindra Bank         123456        SAVINGS
97      3285                    HDFC Bank         123456        SAVINGS
98      3290          Union Bank of India         123456        SAVINGS
99      3292          Kotak Mahindra Bank         123456        SAVINGS
100     3264                   ICICI Bank         123456        SAVINGS
101     3299          State Bank of India         123456        SAVINGS
102     3301                   ICICI Bank         123456        SAVINGS
103     3306                   ICICI Bank         123456        SAVINGS
104     3309                    HDFC Bank         123456        SAVINGS
105     3275                    HDFC Bank         123456        SAVINGS
106     3312          Kotak Mahindra Bank         123456        SAVINGS
107     3319                    HDFC Bank         123456        SAVINGS
108     3320                    HDFC Bank         123456        SAVINGS
109     3321                    HDFC Bank         123456        SAVINGS
110     3322                    HDFC Bank         123456        SAVINGS
111     3331                    HDFC Bank         123456        SAVINGS
112     3339           TJSB Sahakari Bank         123456        SAVINGS
113     3337          Kotak Mahindra Bank         123456        SAVINGS
114     3338          State Bank of India         123456        SAVINGS
115     3336                   ICICI Bank         123456        SAVINGS
116     3353                    HDFC Bank         123456        SAVINGS
117     3354                    IDBI Bank         123456        SAVINGS
118     3352          State Bank of India         123456        SAVINGS
119     3357          State Bank of India         123456        SAVINGS
120     3335          State Bank of India         123456        SAVINGS
121     3371                Bank of India         123456        SAVINGS
122     3378                    HDFC Bank         123456        SAVINGS
123     3377                   ICICI Bank         123456        SAVINGS
124     3379          Kotak Mahindra Bank         123456        SAVINGS
125     3374                    HDFC Bank         123456        SAVINGS
126     3388                    HDFC Bank         123456        SAVINGS
127     3366          Kotak Mahindra Bank         123456        SAVINGS
128     3372        Central Bank of India         123456        SAVINGS
129     3363          State Bank of India         123456        SAVINGS
130     3342                    HDFC Bank         123456        SAVINGS
131     3390                   ICICI Bank         123456        SAVINGS
132      510                Not Available  Not Available  Not Available
133     3417                 Federal Bank         123456        SAVINGS
134     3396                   ICICI Bank         123456        SAVINGS
135      538                Not Available  Not Available  Not Available
136     3435                     RBL Bank         123456        SAVINGS
137     3436                    HDFC Bank         123456        SAVINGS
138      545                Not Available  Not Available  Not Available
139      546                Not Available  Not Available  Not Available
140      514                Not Available  Not Available  Not Available
141     3455          Kotak Mahindra Bank         123456        SAVINGS
142      555                Not Available  Not Available  Not Available
143      558                Not Available  Not Available  Not Available
144      559                Not Available  Not Available  Not Available
145     3478                     Yes Bank         123456        SAVINGS
146     3502                    HDFC Bank         123456        SAVINGS
147      569                Not Available  Not Available  Not Available
148     3518                   ICICI Bank         123456        SAVINGS
149     3496          Kotak Mahindra Bank         123456        SAVINGS
150     3519          Bank of Maharashtra         123456        SAVINGS
151     3533          Kotak Mahindra Bank         123456        SAVINGS
152     3537                    HDFC Bank         123456        SAVINGS
153     3541                IndusInd Bank         123456        SAVINGS
154     3550                   ICICI Bank         123456        SAVINGS
155     3557      Jana Small Finance Bank         123456        SAVINGS
156     3589                   ICICI Bank         123456        SAVINGS
157      585                Not Available  Not Available  Not Available
158     3608          State Bank of India         123456        SAVINGS
159     3570                    Axis Bank         123456        SAVINGS
160      627                Not Available  Not Available  Not Available
161     3656                    Axis Bank           1234        SAVINGS
162     3663                   ICICI Bank           1234        SAVINGS
163     3677          Union Bank of India         123456        SAVINGS
164     3864               Bank of Baroda         123456        SAVINGS
165     3870          State Bank of India         123456        SAVINGS
166     3867          State Bank of India         123456        SAVINGS
167     3866                    IDBI Bank         123456        SAVINGS
168     3832          State Bank of India         123456        SAVINGS
169     3890                    HDFC Bank         123456        SAVINGS
170     3878          Union Bank of India         123456        SAVINGS
171     3875                    HDFC Bank         123456        SAVINGS
172     3897                    HDFC Bank         123456        SAVINGS
173     3896                    HDFC Bank         123456        SAVINGS
174     3910                   ICICI Bank         123456        SAVINGS
175     3911                    Axis Bank         123456        SAVINGS
176     3941                   ICICI Bank         123456        SAVINGS
177      837                Not Available  Not Available  Not Available
178     3949                    HDFC Bank         123456        SAVINGS
179     3785                   ICICI Bank         123456        SAVINGS
180     3966                    Citi Bank         123456        SAVINGS
181     3958          State Bank of India         123456        SAVINGS
182     3988          Kotak Mahindra Bank         123456        SAVINGS
183      866                Not Available  Not Available  Not Available
184     4040                   ICICI Bank         123456        SAVINGS
185     4051                    Axis Bank         123456        SAVINGS
186     3990          State Bank of India         123456        SAVINGS
187     4058                    HDFC Bank         123456        SAVINGS
188     4059          State Bank of India         123456        SAVINGS
189     4039                    Axis Bank         123456        SAVINGS
190     4060                Bank of India         123456        SAVINGS
191     4061                    IDBI Bank         123456        SAVINGS
192     4037               Bank of Baroda         123456        SAVINGS
193     4066  Abhyudaya Co-operative Bank         123456        SAVINGS
194     4072                    Axis Bank         123456        SAVINGS
195     4064          State Bank of India         123456        SAVINGS
196     4074                    Citi Bank         123456        SAVINGS
197     4080                Bank of India         123456        SAVINGS
198     4083                Bank of India         123456        SAVINGS
199     4068                    HDFC Bank         123456        SAVINGS
200     4084          State Bank of India         123456        SAVINGS
201     4053                Bank of India         123456        SAVINGS
202     4041          State Bank of India         123456        SAVINGS
203     4093          State Bank of India         123456        SAVINGS
204     4091          Kotak Mahindra Bank         123456        SAVINGS
205     4062                     J&K Bank         123456        SAVINGS
206     4097          Kotak Mahindra Bank         123456        SAVINGS
207      915                Not Available  Not Available  Not Available
208     4105                   ICICI Bank         123456        SAVINGS
209      897                Not Available  Not Available  Not Available
210     4116                   ICICI Bank         123456        SAVINGS
211     4114                   ICICI Bank         123456        SAVINGS
212     4120                    Axis Bank         123456        SAVINGS
213     4090                    HDFC Bank         123456        SAVINGS
214     4126                    HDFC Bank         123456        SAVINGS
215     4128          State Bank of India         123456        SAVINGS
216     4137                    Axis Bank         123456        SAVINGS
217     4139                    HDFC Bank         123456        SAVINGS
218     4141                   ICICI Bank         123456        SAVINGS
219     4136                    HDFC Bank         123456        SAVINGS
220     4140                   ICICI Bank         123456        SAVINGS
221     4118          Kotak Mahindra Bank         123456        SAVINGS
222     4132                     UCO Bank         123456        SAVINGS
223     4101          State Bank of India         123456        SAVINGS
224     4145                    Axis Bank         123456        SAVINGS
225     4131                    HDFC Bank         123456        SAVINGS
226     4147          State Bank of India         123456        SAVINGS
227     4144                    HDFC Bank         123456        SAVINGS
228     3994              IDFC First Bank         123456        SAVINGS
229     4160                    IDBI Bank         123456        SAVINGS
230     4178                    Citi Bank         123456        SAVINGS
231      953                Not Available  Not Available  Not Available
232      990                Not Available  Not Available  Not Available
233     4247                    HDFC Bank         123456        SAVINGS
234     4297                   ICICI Bank         123456        SAVINGS
235     4316                  Canara Bank         123456        SAVINGS
236      967                Not Available  Not Available  Not Available
237     4325                    HDFC Bank         123456        SAVINGS
238     4329                    HDFC Bank          12345        SAVINGS
239     4331                    HDFC Bank          12345        SAVINGS
240     4332                    HDFC Bank          12345        SAVINGS
241     4335          Kotak Mahindra Bank          12345        SAVINGS
242     1014                Not Available  Not Available  Not Available
243     4334                    Axis Bank          12345        SAVINGS
244     1016                Not Available  Not Available  Not Available
245     4343                    Axis Bank          12345        SAVINGS
246     1003                Not Available  Not Available  Not Available
247     1013                Not Available  Not Available  Not Available
248     1018                Not Available  Not Available  Not Available
249     4345                   ICICI Bank          12345        SAVINGS
250     4363          State Bank of India          12345        SAVINGS
251     4365                    Axis Bank          12345        SAVINGS
252     4362          State Bank of India          12345        SAVINGS
253     4360          Kotak Mahindra Bank          12345        SAVINGS
254     4241          State Bank of India          12345        SAVINGS
255     4374                   ICICI Bank          12345        SAVINGS
256     4381                    HDFC Bank          12345        SAVINGS
257     4376          State Bank of India          12345        SAVINGS
258     1029                Not Available  Not Available  Not Available
259     1030                Not Available  Not Available  Not Available
260     4399                    HDFC Bank          12345        SAVINGS
261     4401                    HDFC Bank          12345        SAVINGS
262     4387          State Bank of India          12345        SAVINGS
263     4382                   ICICI Bank          12345        SAVINGS
264     4384          Bank of Maharashtra          12345        SAVINGS
265     4386                    HDFC Bank          12345        SAVINGS
266     4389                    HDFC Bank          12345        SAVINGS
267     4402        Central Bank of India          12345        SAVINGS
268     4400          Bank of Maharashtra          12345        SAVINGS
269     4403         Punjab National Bank          12345        SAVINGS
270     4404                    HDFC Bank          12345        SAVINGS
271     4344         Punjab National Bank          12345        SAVINGS
272     4409                    HDFC Bank         123456        SAVINGS
273     4410   Saraswat Co-operative Bank          12345        SAVINGS
274     4411          Union Bank of India          12345        SAVINGS
275     4413                    HDFC Bank          12345        SAVINGS

In [26]:
tdf.columns=["lead_id","Bank_name","Account_no","Account_type"]

In [27]:
tdf.head()

   lead_id   Bank_name Account_no Account_type
0   240400  ICICI Bank     123456      SAVINGS
1   240422  ICICI Bank     123456      SAVINGS
2   240433  ICICI Bank     123456      SAVINGS
3  2404666  ICICI Bank     123456      SAVINGS
4     2404  ICICI Bank     123456      SAVINGS

In [28]:
tdf

     lead_id                    Bank_name     Account_no   Account_type
0     240400                   ICICI Bank         123456        SAVINGS
1     240422                   ICICI Bank         123456        SAVINGS
2     240433                   ICICI Bank         123456        SAVINGS
3    2404666                   ICICI Bank         123456        SAVINGS
4       2404                   ICICI Bank         123456        SAVINGS
5       2595                    HDFC Bank        1234589        SAVINGS
6       2924                    HDFC Bank         123456        SAVINGS
7       2938                   ICICI Bank         123456        SAVINGS
8       2956   Saraswat Co-operative Bank         123456        SAVINGS
9       2967          State Bank of India         123456        SAVINGS
10      2966                   ICICI Bank         123456        SAVINGS
11      2968                   ICICI Bank         123456        SAVINGS
12      2973                    HDFC Bank         123456        SAVINGS
13      2979                   ICICI Bank         123456        SAVINGS
14      2985               Karnataka Bank         123456        SAVINGS
15      2988                   ICICI Bank         123456        SAVINGS
16      2990                    HDFC Bank         123456        SAVINGS
17      2989                    HDFC Bank         123456        SAVINGS
18      2993          State Bank of India         123456        SAVINGS
19      2996                   ICICI Bank         123456        SAVINGS
20      3003          Kotak Mahindra Bank         123456        SAVINGS
21      3010                Bank of India         123456        SAVINGS
22      3017         Punjab National Bank         123456        SAVINGS
23      3030                   ICICI Bank         123456        SAVINGS
24      3048                    HDFC Bank         123456        SAVINGS
25      3047                    HDFC Bank         123456        SAVINGS
26      3044  Abhyudaya Co-operative Bank         123456        SAVINGS
27      3052                   ICICI Bank         123456        SAVINGS
28      3075          State Bank of India         123456        SAVINGS
29      3076               Bank of Baroda         123456        SAVINGS
30      3083                    HDFC Bank         123456        SAVINGS
31      3026          State Bank of India         123456        SAVINGS
32      3088                    HDFC Bank         123456        SAVINGS
33      3037                    HDFC Bank         123456        SAVINGS
34      3063                    HDFC Bank         123456        SAVINGS
35      3093          State Bank of India         123456        SAVINGS
36      3092                   ICICI Bank         123456        SAVINGS
37      3090                Bank of India         123456        SAVINGS
38      3105               Bank of Baroda         123456        SAVINGS
39      3109               Bank of Baroda         123456        SAVINGS
40      3113                Bank of India         123456        SAVINGS
41      3098                    HDFC Bank         123456        SAVINGS
42      3122                    HDFC Bank         123456        SAVINGS
43      3123                     Yes Bank         123456        SAVINGS
44      3130                   ICICI Bank         123456        SAVINGS
45      3133                Bank of India         123456        SAVINGS
46      3135                    HDFC Bank         123456        SAVINGS
47      3136          Kotak Mahindra Bank         123456        SAVINGS
48      3138                    Citi Bank         123456        SAVINGS
49      3141                    HDFC Bank         123456        SAVINGS
50      3139                   ICICI Bank         123456        SAVINGS
51      3144                    HDFC Bank         123456        SAVINGS
52      3157          State Bank of India         123456        SAVINGS
53      3154                   ICICI Bank         123456        SAVINGS
54      3148                    HDFC Bank         123456        SAVINGS
55      3163          Kotak Mahindra Bank         123456        SAVINGS
56      3146                    HDFC Bank         123456        SAVINGS
57      3170                    Citi Bank         123456        SAVINGS
58      3177                    HDFC Bank         123456        SAVINGS
59      3153                    HDFC Bank         123456        SAVINGS
60      3185                    HDFC Bank         123456        SAVINGS
61      3186               Bank of Baroda         123456        SAVINGS
62      3194                    HDFC Bank         123456        SAVINGS
63      3193                    HDFC Bank         123456        SAVINGS
64      3192          State Bank of India         123456        SAVINGS
65      3187                   ICICI Bank         123456        SAVINGS
66      3184          State Bank of India         123456        SAVINGS
67      3189                    HDFC Bank         123456        SAVINGS
68      3182                    HDFC Bank         123456        SAVINGS
69      3196               Bank of Baroda         123456        SAVINGS
70      3201                   ICICI Bank         123456        SAVINGS
71      3212              IDFC First Bank         123456        SAVINGS
72      3213                   ICICI Bank         123456        SAVINGS
73      3214          State Bank of India         123456        SAVINGS
74      3215                   ICICI Bank         123456        SAVINGS
75      3191          Kotak Mahindra Bank         123456        SAVINGS
76      3221               Bank of Baroda         123456        SAVINGS
77      3225         Punjab National Bank         123456        SAVINGS
78      3229                  Canara Bank         123456        SAVINGS
79      3232                    HDFC Bank         123456        SAVINGS
80      3233                    HDFC Bank         123456        SAVINGS
81      3234                  Canara Bank         123456        SAVINGS
82      3235                    HDFC Bank         123456        SAVINGS
83      3237          Bank of Maharashtra         123456        SAVINGS
84      3242       Janaseva Sahakari Bank         123456        SAVINGS
85      3239          State Bank of India         123456        SAVINGS
86      3250               Bank of Baroda         123456        SAVINGS
87      3255          State Bank of India         123456        SAVINGS
88      3251                Bank of India         123456        SAVINGS
89      3266                    HDFC Bank         123456        SAVINGS
90      3265                    HDFC Bank         123456        SAVINGS
91      3262          State Bank of India         123456        SAVINGS
92      3272                    HDFC Bank         123456        SAVINGS
93      3279                    HDFC Bank         123456        SAVINGS
94      3273          State Bank of India         123456        SAVINGS
95      3282                    HDFC Bank         123456        SAVINGS
96      3283          Kotak Mahindra Bank         123456        SAVINGS
97      3285                    HDFC Bank         123456        SAVINGS
98      3290          Union Bank of India         123456        SAVINGS
99      3292          Kotak Mahindra Bank         123456        SAVINGS
100     3264                   ICICI Bank         123456        SAVINGS
101     3299          State Bank of India         123456        SAVINGS
102     3301                   ICICI Bank         123456        SAVINGS
103     3306                   ICICI Bank         123456        SAVINGS
104     3309                    HDFC Bank         123456        SAVINGS
105     3275                    HDFC Bank         123456        SAVINGS
106     3312          Kotak Mahindra Bank         123456        SAVINGS
107     3319                    HDFC Bank         123456        SAVINGS
108     3320                    HDFC Bank         123456        SAVINGS
109     3321                    HDFC Bank         123456        SAVINGS
110     3322                    HDFC Bank         123456        SAVINGS
111     3331                    HDFC Bank         123456        SAVINGS
112     3339           TJSB Sahakari Bank         123456        SAVINGS
113     3337          Kotak Mahindra Bank         123456        SAVINGS
114     3338          State Bank of India         123456        SAVINGS
115     3336                   ICICI Bank         123456        SAVINGS
116     3353                    HDFC Bank         123456        SAVINGS
117     3354                    IDBI Bank         123456        SAVINGS
118     3352          State Bank of India         123456        SAVINGS
119     3357          State Bank of India         123456        SAVINGS
120     3335          State Bank of India         123456        SAVINGS
121     3371                Bank of India         123456        SAVINGS
122     3378                    HDFC Bank         123456        SAVINGS
123     3377                   ICICI Bank         123456        SAVINGS
124     3379          Kotak Mahindra Bank         123456        SAVINGS
125     3374                    HDFC Bank         123456        SAVINGS
126     3388                    HDFC Bank         123456        SAVINGS
127     3366          Kotak Mahindra Bank         123456        SAVINGS
128     3372        Central Bank of India         123456        SAVINGS
129     3363          State Bank of India         123456        SAVINGS
130     3342                    HDFC Bank         123456        SAVINGS
131     3390                   ICICI Bank         123456        SAVINGS
132      510                Not Available  Not Available  Not Available
133     3417                 Federal Bank         123456        SAVINGS
134     3396                   ICICI Bank         123456        SAVINGS
135      538                Not Available  Not Available  Not Available
136     3435                     RBL Bank         123456        SAVINGS
137     3436                    HDFC Bank         123456        SAVINGS
138      545                Not Available  Not Available  Not Available
139      546                Not Available  Not Available  Not Available
140      514                Not Available  Not Available  Not Available
141     3455          Kotak Mahindra Bank         123456        SAVINGS
142      555                Not Available  Not Available  Not Available
143      558                Not Available  Not Available  Not Available
144      559                Not Available  Not Available  Not Available
145     3478                     Yes Bank         123456        SAVINGS
146     3502                    HDFC Bank         123456        SAVINGS
147      569                Not Available  Not Available  Not Available
148     3518                   ICICI Bank         123456        SAVINGS
149     3496          Kotak Mahindra Bank         123456        SAVINGS
150     3519          Bank of Maharashtra         123456        SAVINGS
151     3533          Kotak Mahindra Bank         123456        SAVINGS
152     3537                    HDFC Bank         123456        SAVINGS
153     3541                IndusInd Bank         123456        SAVINGS
154     3550                   ICICI Bank         123456        SAVINGS
155     3557      Jana Small Finance Bank         123456        SAVINGS
156     3589                   ICICI Bank         123456        SAVINGS
157      585                Not Available  Not Available  Not Available
158     3608          State Bank of India         123456        SAVINGS
159     3570                    Axis Bank         123456        SAVINGS
160      627                Not Available  Not Available  Not Available
161     3656                    Axis Bank           1234        SAVINGS
162     3663                   ICICI Bank           1234        SAVINGS
163     3677          Union Bank of India         123456        SAVINGS
164     3864               Bank of Baroda         123456        SAVINGS
165     3870          State Bank of India         123456        SAVINGS
166     3867          State Bank of India         123456        SAVINGS
167     3866                    IDBI Bank         123456        SAVINGS
168     3832          State Bank of India         123456        SAVINGS
169     3890                    HDFC Bank         123456        SAVINGS
170     3878          Union Bank of India         123456        SAVINGS
171     3875                    HDFC Bank         123456        SAVINGS
172     3897                    HDFC Bank         123456        SAVINGS
173     3896                    HDFC Bank         123456        SAVINGS
174     3910                   ICICI Bank         123456        SAVINGS
175     3911                    Axis Bank         123456        SAVINGS
176     3941                   ICICI Bank         123456        SAVINGS
177      837                Not Available  Not Available  Not Available
178     3949                    HDFC Bank         123456        SAVINGS
179     3785                   ICICI Bank         123456        SAVINGS
180     3966                    Citi Bank         123456        SAVINGS
181     3958          State Bank of India         123456        SAVINGS
182     3988          Kotak Mahindra Bank         123456        SAVINGS
183      866                Not Available  Not Available  Not Available
184     4040                   ICICI Bank         123456        SAVINGS
185     4051                    Axis Bank         123456        SAVINGS
186     3990          State Bank of India         123456        SAVINGS
187     4058                    HDFC Bank         123456        SAVINGS
188     4059          State Bank of India         123456        SAVINGS
189     4039                    Axis Bank         123456        SAVINGS
190     4060                Bank of India         123456        SAVINGS
191     4061                    IDBI Bank         123456        SAVINGS
192     4037               Bank of Baroda         123456        SAVINGS
193     4066  Abhyudaya Co-operative Bank         123456        SAVINGS
194     4072                    Axis Bank         123456        SAVINGS
195     4064          State Bank of India         123456        SAVINGS
196     4074                    Citi Bank         123456        SAVINGS
197     4080                Bank of India         123456        SAVINGS
198     4083                Bank of India         123456        SAVINGS
199     4068                    HDFC Bank         123456        SAVINGS
200     4084          State Bank of India         123456        SAVINGS
201     4053                Bank of India         123456        SAVINGS
202     4041          State Bank of India         123456        SAVINGS
203     4093          State Bank of India         123456        SAVINGS
204     4091          Kotak Mahindra Bank         123456        SAVINGS
205     4062                     J&K Bank         123456        SAVINGS
206     4097          Kotak Mahindra Bank         123456        SAVINGS
207      915                Not Available  Not Available  Not Available
208     4105                   ICICI Bank         123456        SAVINGS
209      897                Not Available  Not Available  Not Available
210     4116                   ICICI Bank         123456        SAVINGS
211     4114                   ICICI Bank         123456        SAVINGS
212     4120                    Axis Bank         123456        SAVINGS
213     4090                    HDFC Bank         123456        SAVINGS
214     4126                    HDFC Bank         123456        SAVINGS
215     4128          State Bank of India         123456        SAVINGS
216     4137                    Axis Bank         123456        SAVINGS
217     4139                    HDFC Bank         123456        SAVINGS
218     4141                   ICICI Bank         123456        SAVINGS
219     4136                    HDFC Bank         123456        SAVINGS
220     4140                   ICICI Bank         123456        SAVINGS
221     4118          Kotak Mahindra Bank         123456        SAVINGS
222     4132                     UCO Bank         123456        SAVINGS
223     4101          State Bank of India         123456        SAVINGS
224     4145                    Axis Bank         123456        SAVINGS
225     4131                    HDFC Bank         123456        SAVINGS
226     4147          State Bank of India         123456        SAVINGS
227     4144                    HDFC Bank         123456        SAVINGS
228     3994              IDFC First Bank         123456        SAVINGS
229     4160                    IDBI Bank         123456        SAVINGS
230     4178                    Citi Bank         123456        SAVINGS
231      953                Not Available  Not Available  Not Available
232      990                Not Available  Not Available  Not Available
233     4247                    HDFC Bank         123456        SAVINGS
234     4297                   ICICI Bank         123456        SAVINGS
235     4316                  Canara Bank         123456        SAVINGS
236      967                Not Available  Not Available  Not Available
237     4325                    HDFC Bank         123456        SAVINGS
238     4329                    HDFC Bank          12345        SAVINGS
239     4331                    HDFC Bank          12345        SAVINGS
240     4332                    HDFC Bank          12345        SAVINGS
241     4335          Kotak Mahindra Bank          12345        SAVINGS
242     1014                Not Available  Not Available  Not Available
243     4334                    Axis Bank          12345        SAVINGS
244     1016                Not Available  Not Available  Not Available
245     4343                    Axis Bank          12345        SAVINGS
246     1003                Not Available  Not Available  Not Available
247     1013                Not Available  Not Available  Not Available
248     1018                Not Available  Not Available  Not Available
249     4345                   ICICI Bank          12345        SAVINGS
250     4363          State Bank of India          12345        SAVINGS
251     4365                    Axis Bank          12345        SAVINGS
252     4362          State Bank of India          12345        SAVINGS
253     4360          Kotak Mahindra Bank          12345        SAVINGS
254     4241          State Bank of India          12345        SAVINGS
255     4374                   ICICI Bank          12345        SAVINGS
256     4381                    HDFC Bank          12345        SAVINGS
257     4376          State Bank of India          12345        SAVINGS
258     1029                Not Available  Not Available  Not Available
259     1030                Not Available  Not Available  Not Available
260     4399                    HDFC Bank          12345        SAVINGS
261     4401                    HDFC Bank          12345        SAVINGS
262     4387          State Bank of India          12345        SAVINGS
263     4382                   ICICI Bank          12345        SAVINGS
264     4384          Bank of Maharashtra          12345        SAVINGS
265     4386                    HDFC Bank          12345        SAVINGS
266     4389                    HDFC Bank          12345        SAVINGS
267     4402        Central Bank of India          12345        SAVINGS
268     4400          Bank of Maharashtra          12345        SAVINGS
269     4403         Punjab National Bank          12345        SAVINGS
270     4404                    HDFC Bank          12345        SAVINGS
271     4344         Punjab National Bank          12345        SAVINGS
272     4409                    HDFC Bank         123456        SAVINGS
273     4410   Saraswat Co-operative Bank          12345        SAVINGS
274     4411          Union Bank of India          12345        SAVINGS
275     4413                    HDFC Bank          12345        SAVINGS